version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: socialmedia
    volumes:
      - ./mysql_scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  mongo:
    image: mongo:latest
    volumes:
      - ./mongo_scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: neo4j/yourStrongPasswordHere  # Make sure this password is at least 8 characters
    ports:
      - "7474:7474"
      - "7687:7687"
